# Generated by Django 4.0.5 on 2022-07-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read post...', max_length=255),
        ),
    ]
